DEVOPS-7812 Добавить в десктопную компоненту PInkRabbitMQ возможность устанавливать произвольные свойства очередей/сообщений
BITERP/PinkRabbitMQ pull request #36
Opened 2021-01-21 12:10 UTC by ipalenov

2021-01-21 12:20 UTC, ripreal requested changes

2021-01-21 12:20 UTC, ripreal commented on PinkRabbitMQWindows/NativeAPI/RabbitMQClient.h
> +	void fillHeadersFromJson(AMQP::Table& headers, const std::string& propsJson);
А почему этот метод публичный? Кажется он обычный приватный утилитарный

2021-01-21 12:20 UTC, ripreal commented on README.md
> +* arguments - Строка - [НЕОБЯЗАТЕЛЬНЫЙ] произвольные свойства в формате Json-объект. Пример: `{"x-message-ttl": 60000}`.
Т.к. это публичный репозиторий, кинь ссылку на оф. документацию со списком доступных заголовков.

2021-01-21 12:20 UTC, ripreal commented on README.md
> +* arguments - Строка - [НЕОБЯЗАТЕЛЬНЫЙ] произвольные свойства в формате Json-объект. Пример: `{"x-message-ttl": 60000}`.
Т.к. это публичный репозиторий, кинь ссылку на оф. документацию со списком доступных заголовков.

2021-01-21 12:20 UTC, ripreal commented on README.md
> +* arguments - Строка - [НЕОБЯЗАТЕЛЬНЫЙ] произвольные свойства в формате Json-объект. Пример: `{"x-match": "all"}`.
Т.к. это публичный репозиторий, кинь ссылку на оф. документацию со списком доступных заголовков.

2021-01-21 12:20 UTC, ripreal commented on README.md
> +* arguments - Строка - [НЕОБЯЗАТЕЛЬНЫЙ] произвольные свойства в формате Json-объект. Пример: `{"x-message-ttl": 60000}`.
Т.к. это публичный репозиторий, кинь ссылку на оф. документацию со списком доступных заголовков.

2021-01-21 12:22 UTC, ripreal commented on PinkRabbitMQWindows/NativeAPI/RabbitMQClient.cpp
> +	publChannel->publish(exchange, routingKey, envelope);
Ты проверил как метод отрабатывает для решения следующей ошибки: #31 ?

2021-01-21 12:25 UTC, ipalenov commented on PinkRabbitMQWindows/NativeAPI/RabbitMQClient.cpp
> +	publChannel->publish(exchange, routingKey, envelope);
Проверил. Возвращаются ошибки.

2021-01-22 04:51 UTC, ipalenov commented on README.md
> +* arguments - Строка - [НЕОБЯЗАТЕЛЬНЫЙ] произвольные свойства в формате Json-объект. Пример: `{"x-message-ttl": 60000}`.
Добавил ссылку на документацию.

2021-01-22 04:55 UTC, ipalenov commented on README.md
> +* arguments - Строка - [НЕОБЯЗАТЕЛЬНЫЙ] произвольные свойства в формате Json-объект. Пример: `{"x-message-ttl": 60000}`.
Так как x-arguments - это кастомные параметры для серверных расширений rabbitmq, то списка доступных заголовков быть не может. Официальной документации на x-arguments для этого метода нету.

2021-01-22 04:55 UTC, ipalenov commented on README.md
> +* arguments - Строка - [НЕОБЯЗАТЕЛЬНЫЙ] произвольные свойства в формате Json-объект. Пример: `{"x-match": "all"}`.
Официальной документации на x-arguments для этого метода нету.

2021-01-22 04:56 UTC, ipalenov commented on README.md
> +* arguments - Строка - [НЕОБЯЗАТЕЛЬНЫЙ] произвольные свойства в формате Json-объект. Пример: `{"x-message-ttl": 60000}`.
Официальной документации на x-arguments для этого метода нету.

2021-01-22 07:08 UTC, ripreal commented on README.md
> +* arguments - Строка - [НЕОБЯЗАТЕЛЬНЫЙ] произвольные свойства в формате Json-объект. Пример: `{"x-message-ttl": 60000}`.
А как тогда узнать, какие аргументы можно передавать в этот параметр? Если это тсписок изхвестен, то нужно его здесь привести

2021-01-22 07:12 UTC, ripreal commented on PinkRabbitMQWindows/NativeAPI/RabbitMQClient.h
> +	void fillHeadersFromJson(AMQP::Table& headers, const std::string& propsJson);
Вопрос еще актуален

2021-01-22 07:14 UTC, ipalenov commented on PinkRabbitMQWindows/NativeAPI/RabbitMQClient.h
> +	void fillHeadersFromJson(AMQP::Table& headers, const std::string& propsJson);
Я его перенес в приваты. Публичным он получился случайно, когда создавался из меню рефакторинга.

2021-01-22 07:31 UTC, ripreal requested changes

2021-01-22 07:31 UTC, ripreal commented on PinkRabbitMQLinux/src/RabbitMQClient.cpp
>          channelLoc->publish(exchange, routingKey, envelope);
А почему здесь ты не используешь транзакции? Здесь метод оставлен асинхронным? Ошибки с правами будут отлавливаться?

2021-01-22 08:01 UTC, ipalenov commented on PinkRabbitMQLinux/src/RabbitMQClient.cpp
>          channelLoc->publish(exchange, routingKey, envelope);
Завернул publish в транзакцию.

2021-01-22 08:42 UTC, merged